# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# brdr <evelinaorama@gmail.com>, 2015
# Gediminas Golcevas <>, 2014
# Moo, 2015-2018
# Rolandas Barysas <inactive+rb@transifex.com>, 2013-2014
# Tautvydas Zukauskas <lordmu@linuxmail.org>, 2016
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-11-10 15:57+0100\n"
"PO-Revision-Date: 2018-06-02 20:25+0000\n"
"Last-Translator: Moo\n"
"Language-Team: Lithuanian (http://www.transifex.com/otf/torproject/language/lt/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: lt\n"
"Plural-Forms: nplurals=4; plural=(n % 10 == 1 && (n % 100 > 19 || n % 100 < 11) ? 0 : (n % 10 >= 2 && n % 10 <=9) && (n % 100 > 19 || n % 100 < 11) ? 1 : n % 1 != 0 ? 2: 3);\n"

#: ../tails_installer/creator.py:101
msgid "You must run this application as root"
msgstr "Jūs turite paleisti šią programą kaip administratorius"

#: ../tails_installer/creator.py:147
msgid "Extracting live image to the target device..."
msgstr ""

#: ../tails_installer/creator.py:154
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Įrašyta į įrenginį %(speed)d MB/sek. greičiu"

#: ../tails_installer/creator.py:184
msgid "Setting up OLPC boot file..."
msgstr "Nustatomas OLPC paleidimo failas..."

#: ../tails_installer/creator.py:315
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Atsirado problemų, vykdant šią komandą: \"%(command)s\".\nIšsamesnis klaidos žurnalas buvo įrašytas į \"%(filename)s\"."

#: ../tails_installer/creator.py:334
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr ""

#: ../tails_installer/creator.py:338
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr ""

#: ../tails_installer/creator.py:354
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr ""

#: ../tails_installer/creator.py:360
msgid "Unknown ISO, skipping checksum verification"
msgstr "Nežinomas ISO, kontrolinės sumos patikrinimas praleidžiamas"

#: ../tails_installer/creator.py:371
#, python-format
msgid ""
"Not enough free space on device.\n"
"%dMB ISO + %dMB overlay > %dMB free space"
msgstr ""

#: ../tails_installer/creator.py:378
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Kuriama %sMB ilgalaikė perdanga"

#: ../tails_installer/creator.py:439
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Nepavyko nukopijuoti %(infile)s į %(outfile)s: %(message)s"

#: ../tails_installer/creator.py:453
msgid "Removing existing Live OS"
msgstr ""

#: ../tails_installer/creator.py:462 ../tails_installer/creator.py:473
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "Nepavyko atlikti chmod %(file)s: %(message)s"

#: ../tails_installer/creator.py:466
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:478
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:526
#, python-format
msgid "Cannot find device %s"
msgstr "Nepavyksta rasti įrenginio %s"

#: ../tails_installer/creator.py:695
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Nepavyko rašyti į %(device)s, praleidžiama."

#: ../tails_installer/creator.py:719
#, python-format
msgid ""
"Some partitions of the target device %(device)s are mounted. They will be "
"unmounted before starting the installation process."
msgstr "Kai kurie skaidiniai paskirties įrenginyje %(device)s yra prijungti. Prieš pradedant diegimo procesą, jie bus atjungti."

#: ../tails_installer/creator.py:762 ../tails_installer/creator.py:974
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Nežinoma failų sistema. Gali būti, kad jūsų įrenginys turi būti iš naujo formatuotas."

#: ../tails_installer/creator.py:765 ../tails_installer/creator.py:977
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Nepalaikoma failų sistema: %s"

#: ../tails_installer/creator.py:782
#, python-format
msgid "Unknown GLib exception while trying to mount device: %(message)s"
msgstr ""

#: ../tails_installer/creator.py:786
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Nepavyko prijungti įrenginio: %(message)s"

#: ../tails_installer/creator.py:791
msgid "No mount points found"
msgstr "Nerasta prijungimo taškų"

#: ../tails_installer/creator.py:802
#, python-format
msgid "Entering unmount_device for '%(device)s'"
msgstr ""

#: ../tails_installer/creator.py:812
#, python-format
msgid "Unmounting mounted filesystems on '%(device)s'"
msgstr "Atjungiamos failų sistemos ties \"%(device)s\""

#: ../tails_installer/creator.py:816
#, python-format
msgid "Unmounting '%(udi)s' on '%(device)s'"
msgstr "Atjungiama \"%(udi)s\" ties \"%(device)s\""

#: ../tails_installer/creator.py:826
#, python-format
msgid "Mount %s exists after unmounting"
msgstr ""

#: ../tails_installer/creator.py:839
#, python-format
msgid "Partitioning device %(device)s"
msgstr "Skaidomas įrenginys %(device)s"

#: ../tails_installer/creator.py:959
#, python-format
msgid "Unsupported device '%(device)s', please report a bug."
msgstr "Nepalaikomas įrenginys \"%(device)s\", prašome pranešti apie klaidą."

#: ../tails_installer/creator.py:962
msgid "Trying to continue anyway."
msgstr "Bandoma vis tiek tęsti."

#: ../tails_installer/creator.py:971 ../tails_installer/creator.py:1364
msgid "Verifying filesystem..."
msgstr "Tikrinama failų sistema..."

#: ../tails_installer/creator.py:995
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Nepavyko pakeisti tomo etiketės: %(message)s"

#: ../tails_installer/creator.py:1000 ../tails_installer/creator.py:1397
msgid "Installing bootloader..."
msgstr "Diegiama paleidyklė..."

#: ../tails_installer/creator.py:1026
#, python-format
msgid "Could not find the '%s' COM32 module"
msgstr ""

#: ../tails_installer/creator.py:1034 ../tails_installer/creator.py:1415
#, python-format
msgid "Removing %(file)s"
msgstr "Šalinama %(file)s"

#: ../tails_installer/creator.py:1146
#, python-format
msgid "%s already bootable"
msgstr "%s jau ir taip paleidžiamas"

#: ../tails_installer/creator.py:1166
msgid "Unable to find partition"
msgstr "Nepavyko rasti skaidinio"

#: ../tails_installer/creator.py:1189
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Formatuojama %(device)s kaip FAT32"

#: ../tails_installer/creator.py:1249
msgid "Could not find syslinux' gptmbr.bin"
msgstr ""

#: ../tails_installer/creator.py:1262
#, python-format
msgid "Reading extracted MBR from %s"
msgstr ""

#: ../tails_installer/creator.py:1266
#, python-format
msgid "Could not read the extracted MBR from %(path)s"
msgstr ""

#: ../tails_installer/creator.py:1279 ../tails_installer/creator.py:1280
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Atstatomas %s paleidimo įrašas (MBR)"

#: ../tails_installer/creator.py:1285
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Diskas yra kilpinis sujunginys, praleidžiamas MBR atstatymas"

#: ../tails_installer/creator.py:1289 ../tails_installer/creator.py:1543
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Apskaičiuojama %s SHA1 suma"

#: ../tails_installer/creator.py:1314
msgid "Synchronizing data on disk..."
msgstr "Sinchronizuojami duomenys diske..."

#: ../tails_installer/creator.py:1356
msgid "Error probing device"
msgstr ""

#: ../tails_installer/creator.py:1358
msgid "Unable to find any supported device"
msgstr "Nepavyko rasti jokio palaikomo įrenginio"

#: ../tails_installer/creator.py:1368
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr ""

#: ../tails_installer/creator.py:1371
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Nepalaikoma failų sistema: %s\nPrašome padaryti savo USB atmintuko atsarginę kopiją ir formatuoti jį su FAT failų sistema."

#: ../tails_installer/creator.py:1438
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Nepavyko gauti Win32_LogicalDisk; win32com užklausa negrąžino jokių rezultatų"

#: ../tails_installer/creator.py:1491
msgid "Cannot find"
msgstr "Nepavyko rasti"

#: ../tails_installer/creator.py:1492
msgid ""
"Make sure to extract the entire tails-installer zip file before running this"
" program."
msgstr ""

#: ../tails_installer/gui.py:69
#, python-format
msgid "Unknown release: %s"
msgstr "Nežinoma laida: %s"

#: ../tails_installer/gui.py:73
#, python-format
msgid "Downloading %s..."
msgstr "Atsiunčiama %s..."

#: ../tails_installer/gui.py:211
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Klaida: Nepavyksta nustatyti etiketės ar gauti jūsų įrenginio UUID.  Nepavyko tęsti."

#: ../tails_installer/gui.py:258
#, python-format
msgid "Installation complete! (%s)"
msgstr "Diegimas baigtas! (%s)"

#: ../tails_installer/gui.py:263
msgid "Tails installation failed!"
msgstr ""

#: ../tails_installer/gui.py:363
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr ""

#: ../tails_installer/gui.py:375
msgid "Tails Installer"
msgstr ""

#: ../tails_installer/gui.py:456
msgid "Upgrade"
msgstr ""

#: ../tails_installer/gui.py:462 ../data/tails-installer.ui.h:7
msgid "Install"
msgstr ""

#: ../tails_installer/gui.py:469
#, python-format
msgid "%(size)s %(vendor)s %(model)s device (%(device)s)"
msgstr ""

#: ../tails_installer/gui.py:481
msgid "No ISO image selected"
msgstr ""

#: ../tails_installer/gui.py:482
msgid "Please select a Tails ISO image."
msgstr ""

#: ../tails_installer/gui.py:521
msgid "No device suitable to install Tails could be found"
msgstr ""

#: ../tails_installer/gui.py:523
#, python-format
msgid "Please plug a USB flash drive or SD card of at least %0.1f GB."
msgstr ""

#: ../tails_installer/gui.py:557
#, python-format
msgid ""
"The USB stick \"%(pretty_name)s\" is configured as non-removable by its "
"manufacturer and Tails will fail to start on it. Please try installing on a "
"different model."
msgstr ""

#: ../tails_installer/gui.py:567
#, python-format
msgid ""
"The device \"%(pretty_name)s\" is too small to install Tails (at least "
"%(size)s GB is required)."
msgstr "Įrenginys \"%(pretty_name)s\" yra pernelyg mažas, kad būtų įdiegta Tails (reikalingas bent %(size)s GB įrenginys)."

#: ../tails_installer/gui.py:589
msgid "An error happened while installing Tails"
msgstr ""

#: ../tails_installer/gui.py:601
msgid "Refreshing releases..."
msgstr ""

#: ../tails_installer/gui.py:606
msgid "Releases updated!"
msgstr ""

#: ../tails_installer/gui.py:648
msgid "Installation complete!"
msgstr "Diegimas baigtas!"

#: ../tails_installer/gui.py:649
msgid "Installation was completed."
msgstr ""

#: ../tails_installer/gui.py:698
msgid "Unable to mount device"
msgstr "Nepavyko prijungti įrenginio"

#: ../tails_installer/gui.py:705 ../tails_installer/gui.py:735
msgid "Confirm the target USB stick"
msgstr ""

#: ../tails_installer/gui.py:706
#, python-format
msgid ""
"%(size)s %(vendor)s %(model)s device (%(device)s)\n"
"\n"
"All data on this USB stick will be lost."
msgstr ""

#: ../tails_installer/gui.py:722
#, python-format
msgid "%(parent_size)s %(vendor)s %(model)s device (%(device)s)"
msgstr ""

#: ../tails_installer/gui.py:730
msgid ""
"\n"
"\n"
"The persistent storage on this USB stick will be preserved."
msgstr ""

#: ../tails_installer/gui.py:731
#, python-format
msgid "%(description)s%(persistence_message)s"
msgstr ""

#: ../tails_installer/gui.py:781
msgid "Download complete!"
msgstr "Atsiuntimas baigtas!"

#: ../tails_installer/gui.py:785
msgid "Download failed: "
msgstr "Atsiuntimas nepavyko: "

#: ../tails_installer/gui.py:786
msgid "You can try again to resume your download"
msgstr "Galite bandyti tęsti atsisiuntimą. "

#: ../tails_installer/gui.py:794
msgid ""
"The selected file is unreadable. Please fix its permissions or select "
"another file."
msgstr ""

#: ../tails_installer/gui.py:800
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr ""

#: ../tails_installer/gui.py:806
#, python-format
msgid "%(filename)s selected"
msgstr "Pasirinktas %(filename)s"

#: ../tails_installer/source.py:28
msgid "Unable to find LiveOS on ISO"
msgstr ""

#: ../tails_installer/source.py:34
#, python-format
msgid "Could not guess underlying block device: %s"
msgstr ""

#: ../tails_installer/source.py:49
#, python-format
msgid ""
"There was a problem executing `%s`.\n"
"%s\n"
"%s"
msgstr ""

#: ../tails_installer/source.py:63
#, python-format
msgid "'%s' does not exist"
msgstr ""

#: ../tails_installer/source.py:65
#, python-format
msgid "'%s' is not a directory"
msgstr ""

#: ../tails_installer/source.py:75
#, python-format
msgid "Skipping '%(filename)s'"
msgstr ""

#: ../tails_installer/utils.py:44
#, python-format
msgid ""
"There was a problem executing `%s`.%s\n"
"%s"
msgstr ""

#: ../tails_installer/utils.py:124
msgid "Could not open device for writing."
msgstr ""

#: ../data/tails-installer.ui.h:1
msgid "Installation Instructions"
msgstr ""

#: ../data/tails-installer.ui.h:2
msgid "Clone the current Tails"
msgstr ""

#: ../data/tails-installer.ui.h:3
msgid "Use a downloaded Tails ISO image"
msgstr ""

#: ../data/tails-installer.ui.h:4
msgid "Select a distribution to download:"
msgstr ""

#: ../data/tails-installer.ui.h:5
msgid "Target USB stick:"
msgstr ""

#: ../data/tails-installer.ui.h:6
msgid "Reinstall (delete all data)"
msgstr ""
