# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Daniele Catanesi <translate@ccielogs.com>, 2009.
# Francesco Tombolini <tombo@adamantio.net>, 2009.
#   <fswitch20@hotmail.com>, 2012.
# mario_santagiuliana <mario@marionline.it>, 2009.
# Michele Orrù <maker.py@gmail.com>, 2012.
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: https://trac.torproject.org/projects/tor\n"
"POT-Creation-Date: 2012-04-13 14:16+0200\n"
"PO-Revision-Date: 2012-10-09 10:45+0000\n"
"Last-Translator: spawned76 <fswitch20@hotmail.com>\n"
"Language-Team: Italian (http://www.transifex.com/projects/p/torproject/language/it/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: it\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../liveusb/gui.py:80
#, python-format
msgid "Unknown release: %s"
msgstr "Release sconosciuta: %s"

#: ../liveusb/gui.py:84
#, python-format
msgid "Downloading %s..."
msgstr "Download di %s in corso"

#: ../liveusb/gui.py:197
#, python-format
msgid "Device is too small: it must be at least %s MiB."
msgstr "La periferica è troppo piccola: deve contenere almeno %s MiB"

#: ../liveusb/gui.py:226
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Errore: Impossibile impostare l'etichetta o ottenere l'UUID del dispositivo. Impossibile continuare."

#: ../liveusb/gui.py:276
#, python-format
msgid "Installation complete! (%s)"
msgstr "Installazione completata! (%s)"

#: ../liveusb/gui.py:281
msgid "LiveUSB creation failed!"
msgstr "LiveUSB creazione fallita!"

#: ../liveusb/gui.py:388
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Attenzione: questo programma necessita dei permessi di amministratore. Per poterlo aprire, fai click destro sull'icona, quindi su \"Proprietà\". Sotto la scheda Compatibilità, click sulla box \"Apri questo programma come Administrator\""

#: ../liveusb/gui.py:413
msgid "Unable to find any USB drive"
msgstr ""

#: ../liveusb/gui.py:521
msgid ""
"Device is not yet mounted, so we cannot determine the amount of free space."
"  Setting a maximum limit of 8G for the persistent storage."
msgstr "Il dispositivo non e' ancora stato montato, quindi non e' stato possibile determinare la quantita' di spazio libero. Verrà impostata una persistenza dati di 8G."

#: ../liveusb/gui.py:528
#, python-format
msgid "No free space on device %(device)s"
msgstr "Spazio insufficiente sulla periferica %(device)s"

#: ../liveusb/gui.py:533
msgid "Partition is FAT16; Restricting overlay size to 2G"
msgstr "La partizione e' in FAT16; Restrizione della dimensione dell'overlay a 2G"

#: ../liveusb/gui.py:577
msgid "Persistent Storage"
msgstr "Persistenza Dati"

#: ../liveusb/gui.py:586
msgid "Installation complete!"
msgstr "Installazione completata!"

#: ../liveusb/gui.py:587
msgid "Installation was completed. Press OK to close this program."
msgstr "L'installazione è stata completata. Premere OK per chiudere il programma."

#: ../liveusb/gui.py:610
msgid ""
"The Master Boot Record on your device is blank. Pressing 'Create Live USB' "
"again will reset the MBR on this device."
msgstr ""

#: ../liveusb/gui.py:624
msgid ""
"Warning: The Master Boot Record on your device does not match your system's "
"syslinux MBR.  If you have trouble booting this stick, try running the "
"liveusb-creator with the --reset-mbr option."
msgstr ""

#: ../liveusb/gui.py:638
msgid "Unable to mount device"
msgstr "Impossibile montare il dispositivo"

#: ../liveusb/gui.py:644
msgid "Warning: All data on the selected drive will be lost."
msgstr "Attenzione: Tutti i dati sull'unità selezionata saranno persi."

#: ../liveusb/gui.py:646 ../liveusb/gui.py:663
msgid "Press 'Next' if you wish to continue."
msgstr "Premere 'Avanti' per continuare"

#: ../liveusb/gui.py:648 ../liveusb/gui.py:665
msgid "Next"
msgstr ""

#: ../liveusb/gui.py:658
msgid ""
"Your device already contains a LiveOS.\n"
"If you continue, this will be overwritten."
msgstr "Il dispositivo contiene gia' un LiveOS. \nSe si continua il contenuto del dispositivo verra' sovrascritto."

#: ../liveusb/gui.py:661
msgid ""
"Warning: Creating a new persistent overlay will delete your existing one."
msgstr "Attenzione : La creazione di un overlay persistente eliminira' l'overlay esistente."

#: ../liveusb/gui.py:717
msgid "Download complete!"
msgstr "Download completo!"

#: ../liveusb/gui.py:721
msgid "Download failed: "
msgstr "Download fallito:"

#: ../liveusb/gui.py:722
msgid "You can try again to resume your download"
msgstr "E' possibile tentare di ripristinare il download"

#: ../liveusb/gui.py:728
msgid "Select Live ISO"
msgstr "Selezionare Live ISO"

#: ../liveusb/gui.py:731
msgid ""
"The selected file is unreadable.Please fix its permissions or select another"
" file."
msgstr ""

#: ../liveusb/gui.py:737
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr ""

#: ../liveusb/gui.py:743
#, python-format
msgid "%(filename)s selected"
msgstr ""

#: ../liveusb/creator.py:91
msgid "You must run this application as root"
msgstr "Occorre avere i privilegi di root per eseguire questa applicazione"

#: ../liveusb/creator.py:130
msgid ""
"Source type does not support verification of ISO MD5 checksum, skipping"
msgstr ""

#: ../liveusb/creator.py:132
msgid "Verifying ISO MD5 checksum"
msgstr "Verifica del checksum MD5 del file ISO"

#: ../liveusb/creator.py:137
msgid "ISO MD5 checksum verification failed"
msgstr ""

#: ../liveusb/creator.py:139
msgid "ISO MD5 checksum passed"
msgstr ""

#: ../liveusb/creator.py:144
msgid "Extracting live image to USB device..."
msgstr "Estrazione dell'immagine nel dispositivo..."

#: ../liveusb/creator.py:151
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr ""

#: ../liveusb/creator.py:181
msgid "Setting up OLPC boot file..."
msgstr "Configurazione del file di boot OLPC..."

#: ../liveusb/creator.py:365
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr ""

#: ../liveusb/creator.py:384
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr ""

#: ../liveusb/creator.py:388
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr ""

#: ../liveusb/creator.py:404
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Errore: Lo SHA1 del Live CD non e' valido. E' possibile eseguire il programma con l'opzione --noverify per non esegurie la verifica."

#: ../liveusb/creator.py:410
msgid "Unknown ISO, skipping checksum verification"
msgstr "Immagine ISO sconosciuta non verra' eseguita la verifica del checksum"

#: ../liveusb/creator.py:421
msgid "Not enough free space on device."
msgstr "Spazio libero sul dispositivo insufficiente."

#: ../liveusb/creator.py:428
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Creazione overlay persistente %s MB..."

#: ../liveusb/creator.py:487
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr ""

#: ../liveusb/creator.py:497
msgid "Removing existing Live OS"
msgstr ""

#: ../liveusb/creator.py:506 ../liveusb/creator.py:517
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr ""

#: ../liveusb/creator.py:510
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr ""

#: ../liveusb/creator.py:522
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr ""

#: ../liveusb/creator.py:573
#, python-format
msgid "Cannot find device %s"
msgstr "Impossibile trovare il dispositivo %s"

#: ../liveusb/creator.py:635
msgid ""
"You are using an old version of syslinux-extlinux that does not support the "
"ext4 filesystem"
msgstr ""

#: ../liveusb/creator.py:718
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr ""

#: ../liveusb/creator.py:737
#, python-format
msgid ""
"Some partitions of USB device %(device)s are mounted. They will be unmounted"
" before starting the installation process."
msgstr ""

#: ../liveusb/creator.py:786 ../liveusb/creator.py:886
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr ""

#: ../liveusb/creator.py:789
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"In case you are trying to upgrade a manually installed Tails system (that is, if it was installed without this installer), this option is not supported: you need to install it anew to start with, e.g. by choosing the \"Clone Tails\" action instead."
msgstr ""

#: ../liveusb/creator.py:791 ../liveusb/creator.py:889
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Filesystem non supportato: %s"

#: ../liveusb/creator.py:807
#, python-format
msgid "Unknown dbus exception while trying to mount device: %(message)s"
msgstr ""

#: ../liveusb/creator.py:811
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr ""

#: ../liveusb/creator.py:823
msgid "No mount points found"
msgstr ""

#: ../liveusb/creator.py:834
#, python-format
msgid "Unmounting %(device)s"
msgstr ""

#: ../liveusb/creator.py:846
#, python-format
msgid "Mount %s exists after unmounting"
msgstr ""

#: ../liveusb/creator.py:883 ../liveusb/creator.py:1203
msgid "Verifying filesystem..."
msgstr "Verifica del filesystem in corso..."

#: ../liveusb/creator.py:907
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr ""

#: ../liveusb/creator.py:912 ../liveusb/creator.py:1236
msgid "Installing bootloader..."
msgstr ""

#: ../liveusb/creator.py:935 ../liveusb/creator.py:1254
#, python-format
msgid "Removing %(file)s"
msgstr ""

#: ../liveusb/creator.py:1017
#, python-format
msgid "%s already bootable"
msgstr ""

#: ../liveusb/creator.py:1037
msgid "Unable to find partition"
msgstr ""

#: ../liveusb/creator.py:1060
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr ""

#: ../liveusb/creator.py:1109
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr ""

#: ../liveusb/creator.py:1112
msgid ""
"Unable to reset MBR.  You may not have the `syslinux` package installed."
msgstr ""

#: ../liveusb/creator.py:1115
msgid "Drive is a loopback, skipping MBR reset"
msgstr ""

#: ../liveusb/creator.py:1119 ../liveusb/creator.py:1382
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr ""

#: ../liveusb/creator.py:1143
msgid "Synchronizing data on disk..."
msgstr ""

#: ../liveusb/creator.py:1195
msgid "Error probing device"
msgstr ""

#: ../liveusb/creator.py:1197
msgid "Unable to find any removable device"
msgstr ""

#: ../liveusb/creator.py:1207
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Assicurarsi che il pendrive USB sia collegato e formattato con filesystem FAT"

#: ../liveusb/creator.py:1210
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Filesystem non supportato: %s\nEseguire un backup e formattare il pendrive USB con il filesystem FAT."

#: ../liveusb/creator.py:1277
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr ""

#: ../liveusb/creator.py:1330
msgid "Cannot find"
msgstr "Impossibile trovare"

#: ../liveusb/creator.py:1331
msgid ""
"Make sure to extract the entire liveusb-creator zip file before running this"
" program."
msgstr ""
