# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
# Carlos Capote <carloscapote@masticable.org>, 2012.
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: https://trac.torproject.org/projects/tor\n"
"POT-Creation-Date: 2012-04-13 14:16+0200\n"
"PO-Revision-Date: 2012-10-06 17:52+0000\n"
"Last-Translator: Carlos Capote <carloscapote@masticable.org>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/torproject/language/es/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../liveusb/gui.py:80
#, python-format
msgid "Unknown release: %s"
msgstr "Versión desconocida: %s"

#: ../liveusb/gui.py:84
#, python-format
msgid "Downloading %s..."
msgstr "Descargando %s..."

#: ../liveusb/gui.py:197
#, python-format
msgid "Device is too small: it must be at least %s MiB."
msgstr "El dispositivo es demasiado pequeño: debe ser de, al menos %s MB."

#: ../liveusb/gui.py:226
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Error: No se pudo etiquetar u obtener el UUID de su dispositivo. No se puede continuar."

#: ../liveusb/gui.py:276
#, python-format
msgid "Installation complete! (%s)"
msgstr "¡Instalación completa! (%s)"

#: ../liveusb/gui.py:281
msgid "LiveUSB creation failed!"
msgstr "La creación del USB Vivo falló."

#: ../liveusb/gui.py:388
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Advertencia: Esta herramienta debe ser ejecutada por un Administrador. Para hacerlo, haz clic con el botón derecho en el icono y abre las Propiedades. Bajo la pestaña de Compatibilidad, marca la casilla \"Ejecutar este programa como un administrador\"."

#: ../liveusb/gui.py:413
msgid "Unable to find any USB drive"
msgstr "No se encontró ninguna unidad USB"

#: ../liveusb/gui.py:521
msgid ""
"Device is not yet mounted, so we cannot determine the amount of free space."
"  Setting a maximum limit of 8G for the persistent storage."
msgstr "El dispositivo no está montado todavía, por lo que no se puede determinar el espacio libre. Se pondrá un límite máximo de 8G para el almacenamiento persistente."

#: ../liveusb/gui.py:528
#, python-format
msgid "No free space on device %(device)s"
msgstr "No hay espacio libre en el dispositivo %(device)s"

#: ../liveusb/gui.py:533
msgid "Partition is FAT16; Restricting overlay size to 2G"
msgstr "La partición es FAT16; Restringiendo el tamaño del overlay a 2G"

#: ../liveusb/gui.py:577
msgid "Persistent Storage"
msgstr "Almacenamiento Persistente"

#: ../liveusb/gui.py:586
msgid "Installation complete!"
msgstr "¡Instalación completa!"

#: ../liveusb/gui.py:587
msgid "Installation was completed. Press OK to close this program."
msgstr "Instalación completa. Pulsa OK para cerrar este programa."

#: ../liveusb/gui.py:610
msgid ""
"The Master Boot Record on your device is blank. Pressing 'Create Live USB' "
"again will reset the MBR on this device."
msgstr "El registro de arranque principal (MBR) de tu dispositivo está en blanco. Al pulsar 'Crear Live USB' de nuevo, se reseteará el MBR de este dispositivo."

#: ../liveusb/gui.py:624
msgid ""
"Warning: The Master Boot Record on your device does not match your system's "
"syslinux MBR.  If you have trouble booting this stick, try running the "
"liveusb-creator with the --reset-mbr option."
msgstr ""

#: ../liveusb/gui.py:638
msgid "Unable to mount device"
msgstr "No se pudo montar el dispositivo"

#: ../liveusb/gui.py:644
msgid "Warning: All data on the selected drive will be lost."
msgstr "Advertencia: Se perderán todos los datos de la unidad seleccionada."

#: ../liveusb/gui.py:646 ../liveusb/gui.py:663
msgid "Press 'Next' if you wish to continue."
msgstr "Pulsa 'Siguiente' si quieres continuar"

#: ../liveusb/gui.py:648 ../liveusb/gui.py:665
msgid "Next"
msgstr "Siguiente"

#: ../liveusb/gui.py:658
msgid ""
"Your device already contains a LiveOS.\n"
"If you continue, this will be overwritten."
msgstr "Su dispositivo ya contiene un SO Vivo.\nSi continua, se sobreescribirá."

#: ../liveusb/gui.py:661
msgid ""
"Warning: Creating a new persistent overlay will delete your existing one."
msgstr "Advertencia: La creación de un overlay persistente borrará el actual existente."

#: ../liveusb/gui.py:717
msgid "Download complete!"
msgstr "¡Descarga completa!"

#: ../liveusb/gui.py:721
msgid "Download failed: "
msgstr "Falló la descarga:"

#: ../liveusb/gui.py:722
msgid "You can try again to resume your download"
msgstr "Puede intentar de nuevo reasumir la descarga"

#: ../liveusb/gui.py:728
msgid "Select Live ISO"
msgstr "Seleccione ISO Vivo"

#: ../liveusb/gui.py:731
msgid ""
"The selected file is unreadable.Please fix its permissions or select another"
" file."
msgstr "No se puede leer el fichero seleccionado. Por favor, corrige los permisos o elige otro fichero."

#: ../liveusb/gui.py:737
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Imposible utilizar el fichero seleccionado. Puede que tengas más suerte si mueves la ISO a la carpeta raíz de tu unidad (por ejemplo, C:\\)"

#: ../liveusb/gui.py:743
#, python-format
msgid "%(filename)s selected"
msgstr "%(filename)s seleccionados"

#: ../liveusb/creator.py:91
msgid "You must run this application as root"
msgstr "Debe ejecutar esta aplicación como root"

#: ../liveusb/creator.py:130
msgid ""
"Source type does not support verification of ISO MD5 checksum, skipping"
msgstr ""

#: ../liveusb/creator.py:132
msgid "Verifying ISO MD5 checksum"
msgstr "Verificando la suma MD5 del ISO"

#: ../liveusb/creator.py:137
msgid "ISO MD5 checksum verification failed"
msgstr "Falló la verificación ISO MD5"

#: ../liveusb/creator.py:139
msgid "ISO MD5 checksum passed"
msgstr "Verificación ISO MD5 pasada con éxito"

#: ../liveusb/creator.py:144
msgid "Extracting live image to USB device..."
msgstr "Extrayendo la imágen viva en el dispositivo USB..."

#: ../liveusb/creator.py:151
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Escrito el dispositivo a %(speed)d MB/sec"

#: ../liveusb/creator.py:181
msgid "Setting up OLPC boot file..."
msgstr "Configurando un archivo OLPC de arranque..."

#: ../liveusb/creator.py:365
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Se produjo un error ejecutando el siguiente comando: `%(command)s`.\nUn log más detallado del error ha sido escrito en '%(filename)s'."

#: ../liveusb/creator.py:384
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr ""

#: ../liveusb/creator.py:388
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr ""

#: ../liveusb/creator.py:404
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Error: El SHA1 de su CD Vivo es inválido. Debe ejecutar este programa con el argumento --noverify para omitir este chequeo de verificación."

#: ../liveusb/creator.py:410
msgid "Unknown ISO, skipping checksum verification"
msgstr "ISO desconocido, omitiendo la verificación de suma"

#: ../liveusb/creator.py:421
msgid "Not enough free space on device."
msgstr "No hay suficiente espacio libre en el dispositivo."

#: ../liveusb/creator.py:428
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Creando %s MB de overlay persistente"

#: ../liveusb/creator.py:487
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr ""

#: ../liveusb/creator.py:497
msgid "Removing existing Live OS"
msgstr "Eliminando Live OS"

#: ../liveusb/creator.py:506 ../liveusb/creator.py:517
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "No se pudo ejecutar chmod %(file)s: %(message)s"

#: ../liveusb/creator.py:510
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr ""

#: ../liveusb/creator.py:522
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr ""

#: ../liveusb/creator.py:573
#, python-format
msgid "Cannot find device %s"
msgstr "No se pudo encontrar el dispositivo %s"

#: ../liveusb/creator.py:635
msgid ""
"You are using an old version of syslinux-extlinux that does not support the "
"ext4 filesystem"
msgstr ""

#: ../liveusb/creator.py:718
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Imposible escribir en %(device)s, ignorando."

#: ../liveusb/creator.py:737
#, python-format
msgid ""
"Some partitions of USB device %(device)s are mounted. They will be unmounted"
" before starting the installation process."
msgstr ""

#: ../liveusb/creator.py:786 ../liveusb/creator.py:886
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Sistema de ficheros no conocido. Debe reformatearse el dispositivo."

#: ../liveusb/creator.py:789
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"In case you are trying to upgrade a manually installed Tails system (that is, if it was installed without this installer), this option is not supported: you need to install it anew to start with, e.g. by choosing the \"Clone Tails\" action instead."
msgstr ""

#: ../liveusb/creator.py:791 ../liveusb/creator.py:889
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Sistema de archivos no soportado: %s"

#: ../liveusb/creator.py:807
#, python-format
msgid "Unknown dbus exception while trying to mount device: %(message)s"
msgstr ""

#: ../liveusb/creator.py:811
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr ""

#: ../liveusb/creator.py:823
msgid "No mount points found"
msgstr "No se encontraron puntos de montaje"

#: ../liveusb/creator.py:834
#, python-format
msgid "Unmounting %(device)s"
msgstr "Desmontando %(device)s"

#: ../liveusb/creator.py:846
#, python-format
msgid "Mount %s exists after unmounting"
msgstr ""

#: ../liveusb/creator.py:883 ../liveusb/creator.py:1203
msgid "Verifying filesystem..."
msgstr "Verificando sistema de archivo..."

#: ../liveusb/creator.py:907
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Imposible cambiar el nombre del volumen: %(message)s"

#: ../liveusb/creator.py:912 ../liveusb/creator.py:1236
msgid "Installing bootloader..."
msgstr "Instalando bootloader..."

#: ../liveusb/creator.py:935 ../liveusb/creator.py:1254
#, python-format
msgid "Removing %(file)s"
msgstr "Eliminando %(file)s"

#: ../liveusb/creator.py:1017
#, python-format
msgid "%s already bootable"
msgstr "%s ya es de arranque"

#: ../liveusb/creator.py:1037
msgid "Unable to find partition"
msgstr "No se pudo encontrar la partición"

#: ../liveusb/creator.py:1060
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Formateando %(device)s como FAT32"

#: ../liveusb/creator.py:1109
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Reestableciendo el MBR de %s"

#: ../liveusb/creator.py:1112
msgid ""
"Unable to reset MBR.  You may not have the `syslinux` package installed."
msgstr ""

#: ../liveusb/creator.py:1115
msgid "Drive is a loopback, skipping MBR reset"
msgstr ""

#: ../liveusb/creator.py:1119 ../liveusb/creator.py:1382
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Calculando el SHA1 de %s"

#: ../liveusb/creator.py:1143
msgid "Synchronizing data on disk..."
msgstr "Sincronizando datos en el disco..."

#: ../liveusb/creator.py:1195
msgid "Error probing device"
msgstr "Error probando el dispositivo"

#: ../liveusb/creator.py:1197
msgid "Unable to find any removable device"
msgstr "No se pudo encontrar ningún dispositivo extraíble"

#: ../liveusb/creator.py:1207
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Asegúrese de que su unidad USB está conectado y formateado con el sistema de archivo FAT"

#: ../liveusb/creator.py:1210
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Sistema de archivo no soportado: %s\nPor favor, respalde y de formato a su disco USB con el sistema de archivos FAT."

#: ../liveusb/creator.py:1277
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr ""

#: ../liveusb/creator.py:1330
msgid "Cannot find"
msgstr "No se pudo encontrar"

#: ../liveusb/creator.py:1331
msgid ""
"Make sure to extract the entire liveusb-creator zip file before running this"
" program."
msgstr ""
