# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# 
# Translators:
#  arpalord <arpalord@gmail.com>, 2012.
# Charles-Antoine Couret, 2009.
# Charles-Antoine Couret <cacouret@wanadoo.fr>, 2009.
# Eric lassauge <lassauge {AT} users {dot} sourceforge {dot} net>, 2010.
# Michael Ughetto <telimektar1er@gmail.com>, 2008.
# Pablo Martin-Gomez <pablo.martin-gomez@laposte.net>, 2008.
msgid ""
msgstr ""
"Project-Id-Version: The Tor Project\n"
"Report-Msgid-Bugs-To: https://trac.torproject.org/projects/tor\n"
"POT-Creation-Date: 2012-04-13 14:16+0200\n"
"PO-Revision-Date: 2012-10-17 07:48+0000\n"
"Last-Translator: arpalord <arpalord@gmail.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: fr\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../liveusb/gui.py:80
#, python-format
msgid "Unknown release: %s"
msgstr "Version inconnue : %s"

#: ../liveusb/gui.py:84
#, python-format
msgid "Downloading %s..."
msgstr "Téléchargement de %s..."

#: ../liveusb/gui.py:197
#, python-format
msgid "Device is too small: it must be at least %s MiB."
msgstr "Le périphérique est trop petit : il doit faire au moins %s MiB."

#: ../liveusb/gui.py:226
msgid ""
"Error: Cannot set the label or obtain the UUID of your device.  Unable to "
"continue."
msgstr "Erreur : impossible de configurer le label ou d'obtenir l'UUID du périphérique. Impossible de continuer."

#: ../liveusb/gui.py:276
#, python-format
msgid "Installation complete! (%s)"
msgstr "Installation terminée ! (%s)"

#: ../liveusb/gui.py:281
msgid "LiveUSB creation failed!"
msgstr "Échec lors de la création du Live USB !"

#: ../liveusb/gui.py:388
msgid ""
"Warning: This tool needs to be run as an Administrator. To do this, right "
"click on the icon and open the Properties. Under the Compatibility tab, "
"check the \"Run this program as an administrator\" box."
msgstr "Attention : cet outil doit être lancé en tant qu'Administrateur. Pour cela, clic-droit sur l'icône et ouvrez les Propriétés. Dans l'onglet Compatibilité, cochez la case \"Lancer ce programme en tant qu'Administrateur\"."

#: ../liveusb/gui.py:413
msgid "Unable to find any USB drive"
msgstr "Impossible de trouver un lecteur USB"

#: ../liveusb/gui.py:521
msgid ""
"Device is not yet mounted, so we cannot determine the amount of free space."
"  Setting a maximum limit of 8G for the persistent storage."
msgstr "Le périphérique n'est pas monté, impossible de déterminer la place disponible. Choix d'une limite maximale de 8 Go pour le stockage persistant."

#: ../liveusb/gui.py:528
#, python-format
msgid "No free space on device %(device)s"
msgstr "Espace libre insuffisant sur le périphérique %(device)s."

#: ../liveusb/gui.py:533
msgid "Partition is FAT16; Restricting overlay size to 2G"
msgstr "La partition est de type FAT16, la zone de stockage persistant est donc restreinte à 2 Go"

#: ../liveusb/gui.py:577
msgid "Persistent Storage"
msgstr "Stockage persistant"

#: ../liveusb/gui.py:586
msgid "Installation complete!"
msgstr "Installation terminée !"

#: ../liveusb/gui.py:587
msgid "Installation was completed. Press OK to close this program."
msgstr "L'installation est terminée. Appuyez sur OK pour fermer ce programme."

#: ../liveusb/gui.py:610
msgid ""
"The Master Boot Record on your device is blank. Pressing 'Create Live USB' "
"again will reset the MBR on this device."
msgstr "Le « Master Boot Record » de votre périphérique est vide. En cliquant sur « Créez le Live USB » une fois de plus, ce MBR sera réinitialisé."

#: ../liveusb/gui.py:624
msgid ""
"Warning: The Master Boot Record on your device does not match your system's "
"syslinux MBR.  If you have trouble booting this stick, try running the "
"liveusb-creator with the --reset-mbr option."
msgstr "Attention : le « Master Boot Record » de votre périphérique ne correspond pas à celui de votre syslinux. Si vous avez des problèmes à démarrer sur cette clé USB, essayer de lancer usb-creator avec l'option « --reset-mbr »."

#: ../liveusb/gui.py:638
msgid "Unable to mount device"
msgstr "Impossible de monter le périphérique"

#: ../liveusb/gui.py:644
msgid "Warning: All data on the selected drive will be lost."
msgstr "Attention : toutes les données présentes sur le périphérique sélectionné seront perdues."

#: ../liveusb/gui.py:646 ../liveusb/gui.py:663
msgid "Press 'Next' if you wish to continue."
msgstr "Appuyez sur « Suivant » si vous voulez continuer."

#: ../liveusb/gui.py:648 ../liveusb/gui.py:665
msgid "Next"
msgstr "Suivant"

#: ../liveusb/gui.py:658
msgid ""
"Your device already contains a LiveOS.\n"
"If you continue, this will be overwritten."
msgstr "Votre périphérique contient déjà un système d'exploitation Live.\nSi vous continuez, il sera écrasé."

#: ../liveusb/gui.py:661
msgid ""
"Warning: Creating a new persistent overlay will delete your existing one."
msgstr "Attention : la création d'une nouvelle zone de stockage persistant supprimera celle déjà existante."

#: ../liveusb/gui.py:717
msgid "Download complete!"
msgstr "Téléchargement terminé !"

#: ../liveusb/gui.py:721
msgid "Download failed: "
msgstr "Échec du téléchargement : "

#: ../liveusb/gui.py:722
msgid "You can try again to resume your download"
msgstr "Vous pouvez essayer de reprendre votre téléchargement"

#: ../liveusb/gui.py:728
msgid "Select Live ISO"
msgstr "Sélectionnez l'ISO Live"

#: ../liveusb/gui.py:731
msgid ""
"The selected file is unreadable.Please fix its permissions or select another"
" file."
msgstr "Le fichier sélectionné est illisible. Merci de corriger les permissions ou sélectionnez un autre fichier."

#: ../liveusb/gui.py:737
msgid ""
"Unable to use the selected file.  You may have better luck if you move your "
"ISO to the root of your drive (ie: C:\\)"
msgstr "Impossible d'utiliser le fichier sélectionné. Vous devriez avoir plus de chance en déplacant l'ISO à la racine de votre disque (par exemple : C:\\)"

#: ../liveusb/gui.py:743
#, python-format
msgid "%(filename)s selected"
msgstr "%(filename)s sélectionné"

#: ../liveusb/creator.py:91
msgid "You must run this application as root"
msgstr "Vous devez exécuter cette application en tant que superutilisateur"

#: ../liveusb/creator.py:130
msgid ""
"Source type does not support verification of ISO MD5 checksum, skipping"
msgstr "Ce type de source ne permet pas la vérification de la somme de contrôle MD5 de l'ISO, passage à l'étape suivante"

#: ../liveusb/creator.py:132
msgid "Verifying ISO MD5 checksum"
msgstr "Vérification de la somme de contrôle MD5 de l'ISO"

#: ../liveusb/creator.py:137
msgid "ISO MD5 checksum verification failed"
msgstr "Échec de la vérification de la somme de contrôle MD5 de l'ISO"

#: ../liveusb/creator.py:139
msgid "ISO MD5 checksum passed"
msgstr "Vérification de la somme de contrôle MD5 de l'ISO réussie"

#: ../liveusb/creator.py:144
msgid "Extracting live image to USB device..."
msgstr "Extraction de l'image Live vers le périphérique USB..."

#: ../liveusb/creator.py:151
#, python-format
msgid "Wrote to device at %(speed)d MB/sec"
msgstr "Écriture sur le périphérique effectuée à %(speed)d MB/sec"

#: ../liveusb/creator.py:181
msgid "Setting up OLPC boot file..."
msgstr "Configuration du fichier d'amorçage de l'OLPC..."

#: ../liveusb/creator.py:365
#, python-format
msgid ""
"There was a problem executing the following command: `%(command)s`.\n"
"A more detailed error log has been written to '%(filename)s'."
msgstr "Un problème est survenu lors de l'exécution de la commande suivante : « %(command)s »\nUn journal d'erreur plus détaillé a été écrit dans le fichier « %(filename)s »"

#: ../liveusb/creator.py:384
msgid "Verifying SHA1 checksum of LiveCD image..."
msgstr "Vérification de la somme de contrôle SHA1 de l'image du Live CD..."

#: ../liveusb/creator.py:388
msgid "Verifying SHA256 checksum of LiveCD image..."
msgstr "Vérification de la somme de contrôle SHA256 de l'image du Live CD..."

#: ../liveusb/creator.py:404
msgid ""
"Error: The SHA1 of your Live CD is invalid.  You can run this program with "
"the --noverify argument to bypass this verification check."
msgstr "Erreur : le SHA1 de votre Live CD est invalide. Vous pouvez exécuter ce programme avec l'option « --noverify » pour contourner cette vérification."

#: ../liveusb/creator.py:410
msgid "Unknown ISO, skipping checksum verification"
msgstr "ISO inconnue, omission de la vérification de la somme de contrôle"

#: ../liveusb/creator.py:421
msgid "Not enough free space on device."
msgstr "Espace libre insuffisant sur le périphérique."

#: ../liveusb/creator.py:428
#, python-format
msgid "Creating %sMB persistent overlay"
msgstr "Création du stockage persistant de %s MB"

#: ../liveusb/creator.py:487
#, python-format
msgid "Unable to copy %(infile)s to %(outfile)s: %(message)s"
msgstr "Impossible de copier %(infile)s vers %(outfile)s : %(message)s"

#: ../liveusb/creator.py:497
msgid "Removing existing Live OS"
msgstr "Suppression du système d'exploitation Live existant"

#: ../liveusb/creator.py:506 ../liveusb/creator.py:517
#, python-format
msgid "Unable to chmod %(file)s: %(message)s"
msgstr "Impossible de changer les permissions de %(file)s : %(message)s"

#: ../liveusb/creator.py:510
#, python-format
msgid "Unable to remove file from previous LiveOS: %(message)s"
msgstr "Impossible d'enlever le fichier du système d'exploitation Live précédent : %(message)s"

#: ../liveusb/creator.py:522
#, python-format
msgid "Unable to remove directory from previous LiveOS: %(message)s"
msgstr "Impossible d'enlever le dossier du système d'exploitation Live précédent : %(message)s"

#: ../liveusb/creator.py:573
#, python-format
msgid "Cannot find device %s"
msgstr "Impossible de trouver le périphérique %s"

#: ../liveusb/creator.py:635
msgid ""
"You are using an old version of syslinux-extlinux that does not support the "
"ext4 filesystem"
msgstr "Vous utilisez une version obsolète de syslinux-extlinux, qui ne permet pas d'utiliser le système de fichiers ext4"

#: ../liveusb/creator.py:718
#, python-format
msgid "Unable to write on %(device)s, skipping."
msgstr "Impossible d'écrire sur %(device)s, passage à l'étape suivante."

#: ../liveusb/creator.py:737
#, python-format
msgid ""
"Some partitions of USB device %(device)s are mounted. They will be unmounted"
" before starting the installation process."
msgstr "Certaines partitions du périphérique USB %(device)s sont montées. Elles vont être démontées avant de commencer le processus d'installation."

#: ../liveusb/creator.py:786 ../liveusb/creator.py:886
msgid "Unknown filesystem.  Your device may need to be reformatted."
msgstr "Système de fichiers inconnu. Votre périphérique doit être reformaté."

#: ../liveusb/creator.py:789
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"In case you are trying to upgrade a manually installed Tails system (that is, if it was installed without this installer), this option is not supported: you need to install it anew to start with, e.g. by choosing the \"Clone Tails\" action instead."
msgstr "Système de fichiers non pris en charge : %s\nDans le cas où vous tentez de mettre à jour un système Tails installé manuellement (c'est-à-dire installé sans cet installeur), cette option n'est pas supportée : vous devez le réinstaller de zéro, par exemple en choisissant l'option \"Cloner Tails\"."

#: ../liveusb/creator.py:791 ../liveusb/creator.py:889
#, python-format
msgid "Unsupported filesystem: %s"
msgstr "Système de fichiers non pris en charge : %s"

#: ../liveusb/creator.py:807
#, python-format
msgid "Unknown dbus exception while trying to mount device: %(message)s"
msgstr "Exception dbus inconnue lors de la tentative de montage du périphérique : %(message)s"

#: ../liveusb/creator.py:811
#, python-format
msgid "Unable to mount device: %(message)s"
msgstr "Impossible de monter le périphérique : %(message)s"

#: ../liveusb/creator.py:823
msgid "No mount points found"
msgstr "Aucun point de montage trouvé"

#: ../liveusb/creator.py:834
#, python-format
msgid "Unmounting %(device)s"
msgstr "Démontage de %(device)s"

#: ../liveusb/creator.py:846
#, python-format
msgid "Mount %s exists after unmounting"
msgstr "Le montage %s existe après démontage"

#: ../liveusb/creator.py:883 ../liveusb/creator.py:1203
msgid "Verifying filesystem..."
msgstr "Vérification du système de fichiers..."

#: ../liveusb/creator.py:907
#, python-format
msgid "Unable to change volume label: %(message)s"
msgstr "Impossible de changer le label du volume : %(message)s"

#: ../liveusb/creator.py:912 ../liveusb/creator.py:1236
msgid "Installing bootloader..."
msgstr "Installation du chargeur de démarrage..."

#: ../liveusb/creator.py:935 ../liveusb/creator.py:1254
#, python-format
msgid "Removing %(file)s"
msgstr "Suppression du fichier %(file)s"

#: ../liveusb/creator.py:1017
#, python-format
msgid "%s already bootable"
msgstr "%s déjà amorçable"

#: ../liveusb/creator.py:1037
msgid "Unable to find partition"
msgstr "Impossible de trouver la partition"

#: ../liveusb/creator.py:1060
#, python-format
msgid "Formatting %(device)s as FAT32"
msgstr "Création d'un système de fichiers FAT32 sur %(device)s"

#: ../liveusb/creator.py:1109
#, python-format
msgid "Resetting Master Boot Record of %s"
msgstr "Réinitialisation du « Master Boot Record » de %s"

#: ../liveusb/creator.py:1112
msgid ""
"Unable to reset MBR.  You may not have the `syslinux` package installed."
msgstr "Impossible de réinitialiser le MBR. Vous n'avez peut-être pas installé le paquet `syslinux` ?"

#: ../liveusb/creator.py:1115
msgid "Drive is a loopback, skipping MBR reset"
msgstr "Le périphérique est un « loopback », on ne gère pas la réinitialisation du MBR"

#: ../liveusb/creator.py:1119 ../liveusb/creator.py:1382
#, python-format
msgid "Calculating the SHA1 of %s"
msgstr "Calcul du SHA1 de %s"

#: ../liveusb/creator.py:1143
msgid "Synchronizing data on disk..."
msgstr "Synchronisation des données sur le disque..."

#: ../liveusb/creator.py:1195
msgid "Error probing device"
msgstr "Erreur lors de l'accès au périphérique"

#: ../liveusb/creator.py:1197
msgid "Unable to find any removable device"
msgstr "Impossible de trouver un périphérique amovible"

#: ../liveusb/creator.py:1207
msgid ""
"Make sure your USB key is plugged in and formatted with the FAT filesystem"
msgstr "Assurez-vous que votre clé USB est branchée et qu'elle est formatée avec le système de fichiers FAT"

#: ../liveusb/creator.py:1210
#, python-format
msgid ""
"Unsupported filesystem: %s\n"
"Please backup and format your USB key with the FAT filesystem."
msgstr "Système de fichiers non pris en charge : %s\nVeuillez sauvegarder le contenu de votre clé USB et la formater avec le système de fichiers FAT."

#: ../liveusb/creator.py:1277
msgid ""
"Unable to get Win32_LogicalDisk; win32com query did not return any results"
msgstr "Impossible d'avoir accès à « Win32_LogicalDisk » ; la requête « win32com » n'a pas fourni de résultat."

#: ../liveusb/creator.py:1330
msgid "Cannot find"
msgstr "Impossible de trouver"

#: ../liveusb/creator.py:1331
msgid ""
"Make sure to extract the entire liveusb-creator zip file before running this"
" program."
msgstr "Assurez-vous d'extraire complètement l'archive zip de liveusb-creator avant d'exécuter ce programme."
